# Generated by Django 4.0 on 2022-08-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watch_again',
            new_name='watchAgain',
        ),
    ]
